version: "3.9"
services:
  postgres:
    image: postgres:13.6
    environment:
      POSTGRES_DB: "gophermart"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
